admin.username=admin
admin.password=admin

apiBaseUrl=http://localhost:4111
apiVersion=/api/v1/

uiRemote=http://localhost:4444/wd/hub
uiBaseUrl=http://192.168.31.215:3000
browser=chrome
browserSize=1920x1080
environment=test